# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

venue1 = Venue.create(name: "10 Chancery Lane Gallery", website: "10chancerylanegallery.com", address: "G/F, 10 Chancery Lane, SoHo", district: "Central")
venue2 = Venue.create(name: "1a Space", website: "http://www.oneaspace.org.hk/gallery.php?cms_id=8", address: "Unit 14, Cattle Depot Artist Village, 63 Ma Tau Kok Road", district: "To Kwa Wan")
venue3 = Venue.create(name: "2P Contemporary Art", website: "2p-gallery.com", address: "Shop 5, GF Poga Building, 6-20 Po Tuck Street", district: "Sai Ying Pun")
venue4 = Venue.create(name: "3812 Contemporary Art Projects", website: "http://www.3812cap.com/", address: "10/F, 12 Wong Chuk Hang Road", district: "Aberdeen")
venue5 = Venue.create(name: "A Gallery", website: "http://www.a-gallery.com.hk/", address: "Cockloft, No. 2-4 Mee Lun Street", district: "Central")
venue6 = Venue.create(name: "A-lift", website: "http://www.a-lift.hk/index2.html", address: "Ft 804 & Ft 1003, Blk A, Wah Luen Industrial Centre, 15-21 Wong Chuk Yeung Street", district: "Sha Tin, NT")
venue7 = Venue.create(name: "Above Second", website: "http://blog.above-second.com/", address: "31 Eastern Street", district: "Sai Ying Pun")
venue8 = Venue.create(name: "Affinity for Art", website: "http://www.affinityforart.com/", address: "1/F, 1 Queen's Road West", district: "Sheung Wan")
venue9 = Venue.create(name: "Aishonanzuka", website: "http://www.aishonanzuka.com/", address: "13A, Regency Center, phase1, 39 Wong Chuk Hang Road", district: "Aberdeen")
venue10 = Venue.create(name: "AJC", website: "http://www.ajc-art.com/", address: "6-10 Shin Hing Street", district: "Central")
venue11 = Venue.create(name: "Alisan Fine Arts", website: "http://www.alisan.com.hk/en/", address: "2305 Hing Wai Centre, 7 Tin Wan Praya Road", district: "Aberdeen")
venue12 = Venue.create(name: "Anna Ning Fine Art", website: "http://www.annaningfineart.com/splash/", address: "101 St. George's Building, 2 Ice House Street", district: "Central")
venue13 = Venue.create(name: "AO Vertical Art Space", website: "http://www.aovertical.com/", address: "1-13/F Asia One Tower, 8 Fung Yip Street", district: "Chai Wan")
venue14 = Venue.create(name: "AP Contemporary", website: "http://www.apcontemporary.com/", address: "28 Tai Ping Shan Street", district: "Sheung Wan")
venue15 = Venue.create(name: "Arch Angel Art", website: "https://plus.google.com/116334491045720512829/about?gl=hk&hl=en", address: "38 Peel Street", district: "Central")
venue16 = Venue.create(name: "Art Beatus Gallery", website: "http://www.artbeatus.com/", address: "G/F, 129-133 Wellington Street", district: "Central")
venue17 = Venue.create(name: "Art Experience Gallery", website: "http://artexperiencegallery.com/", address: "Room 2009, Cable TV Tower, 9 Hoi Shing Road", district: "Tsuen Wan, NT")
venue18 = Venue.create(name: "Art Projects Gallery", website: "http://www.artprojectsasia.com/", address: "Unit S510, 5/F, Block A, PMQ, 35 Aberdeen Street", district: "Central")
venue19 = Venue.create(name: "Art Supermarket", website: "http://www.artsupermarketasia.com/", address: "G/F, 1 Prince's Terrace", district: "Midlevels")
venue20 = Venue.create(name: "Artify Gallery", website: "http://www.artifygallery.com/", address: "Unit 7, 10/F, Block A, Ming Pao Industrial Centre, 18 Ka Yip Street", district: "Chai Wan")
venue21 = Venue.create(name: "Asia Fine Art", website: "http://www.gallery27hk.com/", address: "1901 Harcourt House, 39 Gloucester Road", district: "Wan Chai")
venue22 = Venue.create(name: "Axel Vervoordt Gallery", website: "http://www.axel-vervoordt.com/en/gallery/", address: "15D Entertainment Building 30 Queen's Road", district: "Central")
venue23 = Venue.create(name: "Ben Brown Fine Arts", website: "http://www.benbrownfinearts.com/", address: "301 Pedder Building, 12 Pedder Street", district: "Central")
venue24 = Venue.create(name: "Blindspot Gallery", website: "http://www.blindspotgallery.com/", address: "15/F Po Chai Industrial Building, 28 Wong Chuk Hang Road", district: "Aberdeen")
venue25 = Venue.create(name: "Blue Lotus Gallery", website: "http://www.bluelotus-gallery.com.hk/", address: "Wah Luen Industrial Building G/F Unit 26, 15-21 Wong Chuk Yeung Street", district: "Fotan")
venue26 = Venue.create(name: "CAIS Gallery", website: "http://www.caisgallery.com/v2/exhibition/exhibition.php?id=154&PHPSESSID=ba48a35f3983928db5525ee645ef6401", address: "G/F, 87 Hollywood Road", district: "Central")
venue27 = Venue.create(name: "Connoisseur Art Gallery", website: "http://www.connoisseur-art.com/hkgallery.php#", address: "G3, Chinachem Hollywood Centre, 1 Hollywood Road", district: "Central")
venue28 = Venue.create(name: "Connoisseur Contemporary", website: "http://www.connoisseurcontemporary.com/", address: "G4, Chinachem Hollywood Centre, 1 Hollywood Road", district: "Central")
venue29 = Venue.create(name: "Contemporary By Angela Li", website: "http://www.cbal.com.hk/", address: "G/F, 248 Hollywood Road", district: "Sheung Wan")
venue30 = Venue.create(name: "De Sarthe Gallery", website: "http://www.desarthe.com/", address: "8/F Club Lusitano, 16 Ice House Street", district: "Central")
venue31 = Venue.create(name: "Edouard Malingue Gallery", website: "http://www.edouardmalingue.com/", address: "6/F, 33 Des Voeux Road", district: "Central")
venue32 = Venue.create(name: "Edouard Malingue Gallery", website: "http://www.edouardmalingue.com/", address: "6th Floor, 33 Des Voeux Road", district: "Central")
venue33 = Venue.create(name: "Fabrik Gallery", website: "http://www.fabrik-gallery.com/", address: "1102 Nam Wo Hong Building, 148 Wing Lok Street", district: "Sheung Wan")
venue34 = Venue.create(name: "Feast Projects", website: "feastprojects.com", address: "Unit 307, 3F Harbour Industrial Centre, 10 Lee Hing Street, Ap Lei Chau", district: "Aberdeen")
venue35 = Venue.create(name: "Future Industries", website: "http://www.thefutureindustries.com/", address: "21 Square Street", district: "Sheung Wan")
venue36 = Venue.create(name: "Gagosian", website: "gagosian.com", address: "7F Pedder Building, 12 Pedder Street", district: "Central")
venue37 = Venue.create(name: "Galerie Du Monde", website: "http://www.galeriedumonde.com/home/current/art/", address: "108 Ruttonjee Centre, 11 Duddell Street", district: "Central")
venue38 = Venue.create(name: "Galerie Huit", website: "http://www.galeriehuit.com.hk/", address: "Shop 2, G/F & 1/F, SOHO 189, 189 Queen's Road West", district: "Wanchai")
venue39 = Venue.create(name: "Galerie Koo", website: "http://www.galeriekoo.com/", address: "7/F Vogue Building, 67 Wyndham Street", district: "Central")
venue40 = Venue.create(name: "Galerie Ora-Ora", website: "http://www.ora-ora.com/", address: "G/F, 7 Shin Hing Street", district: "Central")
venue41 = Venue.create(name: "Galerie Perrotin", website: "http://www.galerieperrotin.com/", address: "7/F, 50 Connaught Road", district: "Central")
venue42 = Venue.create(name: "Gallery 27", website: "http://www.asia-fineart.com/exhibitions_and_events.php?event_show=1", address: "H1, 10th Floor
Kwai Shing Industrial Building (Phase 2)42-46 Dai Lin Pai Road", district: "Kwai Chung")
venue43 = Venue.create(name: "Gallery Article", website: "http://www.galleryarticle.com/", address: "1 Shin Hing Street", district: "Central")
venue44 = Venue.create(name: "Gallery Exit", website: "galleryexit.com", address: "3/F, 25 Hing Wo Street, Tin Wan", district: "Aberdeen")
venue45 = Venue.create(name: "Gallery Livi", website: "https://www.facebook.com/pages/Gallery-Livi/139985009435646?sk=info&tab=page_info", address: "5 Ladder Street", district: "Sheung Wan")
venue46 = Venue.create(name: "Green Art Asia", website: "http://greenartasia.com/", address: "Unit 10-11,9/F,K Wah Centre 191 Java Road", district: "North Point")
venue48 = Venue.create(name: "Hanart TZ Gallery", website: "https://www.facebook.com/Hanart.TZ.Gallery/info?tab=overview", address: "407 Pedder Building, 12 Pedder Street", district: "Central")
venue49 = Venue.create(name: "Hong Kong Visual Arts Centre", website: "http://www.lcsd.gov.hk/CE/Museum/APO/en_US/web/apo/va_visit.html#openinghour", address: "7A Kennedy Road", district: "Central")
venue50 = Venue.create(name: "i-dArt", website: "http://i-dart.tungwahcsd.org/", address: "Shop 1, G/F Block 2,
Centenary Mansion, 1 Victoria Road", district: "Kennedy Town")
venue51 = Venue.create(name: "Identity Art Gallery", website: "http://www.identityartgallery.com/", address: "G/F, 53 Tung Street", district: "Sheung Wan")
venue52 = Venue.create(name: "Karin Weber Gallery", website: "http://www.karinwebergallery.com/home/main/en/", address: "G/F, 20 Aberdeen Street", district: "Central")
venue53 = Venue.create(name: "Korkos Gallery", website: "http://www.korkos-gallery.com/index.htm", address: "3 Prince's Terrace", district: "Midlevels")
venue54 = Venue.create(name: "Koru Contemporary Art", website: "http://www.koru-hk.com/home/main/en/", address: "1604 Hing Wai Centre, 7 Tin Wan Praya Road", district: "Aberdeen")
venue55 = Venue.create(name: "Kwai Fung Hin Art Gallery", website: "http://www.kwaifunghin.com/home/current/eng/", address: "G/F, 20 Ice House Street", district: "Central")
venue56 = Venue.create(name: "Lee Wing Tong Gallery", website: "http://liwingtong.com/webapps/map.html", address: "4/F, 97 Des Veoux Road West", district: "Sheung Wan")
venue57 = Venue.create(name: "Lehmann Maupin", website: "http://www.lehmannmaupin.com/", address: "407 Pedder Building, 12 Pedder Street", district: "Central")
venue58 = Venue.create(name: "Leo Gallery", website: "http://www.leogallery.com.cn/", address: "G/F, 189 Queen's Road West", district: "Sai Ying Pun")
venue59 = Venue.create(name: "Mischmasch Gallery", website: "http://www.mischmaschgallery.com/", address: "Unit A 18/F Shing Hing Commercial Building, 21-27 Wing Kut Street", district: "Central")
venue60 = Venue.create(name: "Mur Normade", website: "http://www.murnomade.com/", address: "1606 Hing Wai Centre, 7 Tin Wan Praya Road", district: "Aberdeen")
venue61 = Venue.create(name: "New Gallery on Old Bailey", website: "http://www.ngoob.com/", address: "4/F, 35 Tai Yau St, SPK, Kai Tak", district: "Kowloon")
venue62 = Venue.create(name: "Ooi Botos Gallery", website: "http://www.ooibotos.com/site_U06/index2.html?a=0.857429299503565", address: "N/A", district: "N/A")
venue63 = Venue.create(name: "Opera Gallery", website: "http://www.operagallery.com/", address: "G/F-3/F W Place, 52 Wyndham Street", district: "Central")
venue64 = Venue.create(name: "Osage Gallery", website: "http://www.osagegallery.com/", address: "4/F, Union Hing Yip Factory Building, 20 Hing Yip Street", district: "Kwun Tong, Kowloon")
venue65 = Venue.create(name: "Pace Gallery", website: "http://pacegallery.com/", address: "15C Entertainment Building, 30 Queens Road", district: "Central")
venue66 = Venue.create(name: "Para/Site Art Space", website: "para-site.org.hk", address: "GF 4 Po Yan Street", district: "Sheung Wan")
venue67 = Venue.create(name: "Parkview Art Hong Kong", website: "http://www.parkviewarthk.com/", address: "Shop 6, Upper G/F Sunrise House, 27 Old Bailey Street", district: "Central")
venue68 = Venue.create(name: "Pearl Lam Galleries", website: "http://www.pearllam.com/", address: "601-605 Pedder Building, 12 Pedder Street", district: "Central")
venue69 = Venue.create(name: "Pekin Fine Arts", website: "http://www.pekinfinearts.com/", address: "16/F Union Industrial Building, 48 Wong Chuk Hang Road", district: "Aberdeen")
venue70 = Venue.create(name: "Picture This Gallery", website: "http://www.picturethiscollection.com/home/main/en/", address: "Suite 1308, 9 Queen's Road", district: "Central")
venue71 = Venue.create(name: "Platform China", website: "http://www.platformchina.org/en/index.asp", address: "Unit 601, Chaiwan Industrial City Phase 1, 60 Wing Tai Road", district: "Chai Wan")
venue72 = Venue.create(name: "Plum Blossoms Gallery", website: "http://www.plumblossoms.com/", address: "14/F Cheung Tak Industrial Building, 30 Wong Chuk Hang Road", district: "Aberdeen")
venue73 = Venue.create(name: "PubArt Gallery", website: "http://www.pubart-gallery.com/", address: "G/F 7B Chancery Lane", district: "Central")
venue74 = Venue.create(name: "Puerta Roja Gallery", website: "http://www.puerta-roja.com/", address: "G/F Wai Yue Building, 15-17 New Street", district: "Sheung Wan")
venue75 = Venue.create(name: "Saamlung", website: "saamlung.com", address: "26F Two Chinachem Plaza, 68 Connaught Road", district: "Central")
venue76 = Venue.create(name: "Shin Hwa Gallery", website: "http://www.shinhwagallery.com/", address: "1/F, Mandarin Commercial House, 38 Morrison Hill Road", district: "Wanchai")
venue77 = Venue.create(name: "Simon Lee Gallery", website: "http://www.simonleegallery.com/", address: "304 Pedder Building, 12 Pedder Street", district: "Central")
venue78 = Venue.create(name: "Sin Sin Fine Art", website: "http://www.sinsinfineart.com/", address: "53-54 Sai Street", district: "Central")
venue79 = Venue.create(name: "State-of-the-Arts Gallery", website: "http://www.sotagallery.com.hk/", address: "16A Max Share Center, 371 King's Road", district: "Central")
venue80 = Venue.create(name: "Sundaram Tagore Gallery", website: "http://www.sundaramtagore.com/", address: "57-59 Hollywood Road", district: "Central")
venue81 = Venue.create(name: "The Cat Street Gallery", website: "http://www.thecatstreetgallery.com/", address: "222 Hollywood Road", district: "Sheung Wan")
venue82 = Venue.create(name: "The Gallery of Modern Art", website: "", address: "Shop L115-116, New World Centre, 18-24 Salibury Road", district: "TST")
venue83 = Venue.create(name: "toof Contemporary", website: "http://www.toofcontemporary.com/", address: "3rd floor, 311, CANTEEN, Harbour Industrial Centre,10 Lee Hing Street", district: "Ap Lei Chau")
venue84 = Venue.create(name: "University Museum and Art Gallery - The University of Hong Kong", website: "http://www.hkumag.hku.hk/main.html", address: "90 Bonham Road", district: "Pokfulam")
venue85 = Venue.create(name: "VA Gallery", website: "http://www.va-gallery.com/", address: "Room 1203, 12/F, New Venture Technology Centre, 18 Lam Tin Street", district: "Kwai Chung")
venue86 = Venue.create(name: "Videotage", website: "http://videotage.org.hk/", address: "Unit 13, Cattle Depot Artist Village, 63 Ma Tau Kok Road", district: "To Kwa Wan")
venue87 = Venue.create(name: "Voxfire Gallery", website: "http://www.voxfiregallery.com/home.php", address: "1/F 52 Gage Street", district: "Sheung Wan")
venue88 = Venue.create(name: "Wan Fung Gallery", website: "http://www.wanfung.com.cn/eng/index.asp", address: "3/F, New Lee Wah Centre, 88 To Kwa Wan Road", district: "Kowloon")
venue89 = Venue.create(name: "Wellington Gallery", website: "http://www.wellingtongallery.com.hk/", address: "G/F, 36 Wyndham Street", district: "Central")
venue90 = Venue.create(name: "White Cube", website: "whitecube.com", address: "50 Connaught Road", district: "Central")
venue91 = Venue.create(name: "Yan Gallery", website: "http://yangallery.com/", address: "1/F Chinachem Hollywood Centre, 1 Hollywood Road", district: "Central")
venue92 = Venue.create(name: "YY9 Gallery", website: "http://www.2bsquare.com/", address: "206 Chai Wan Industrial City Phase 1, 60 Wing Tai Road", district: "Chai Wan")
venue93 = Venue.create(name: "Zee Stone Gallery", website: "http://www.zeestone.com/index.php", address: "G/F Chinachem, Hollywood Centre, 1 Hollywood Road", district: "Central")
venue94 = Venue.create(name: "ZZHK Gallery", website: "http://www.zzhkgallery.com/", address: "G/F, 3 Wa Lane", district: "Sheung Wan")



